### ISSUE TITLE
pod install errors in new machine

### ISSUE THREAD

**Issue by vikaschandra** [crelies/AmazonFling#5]
When we install this pod in a machine where old cache is not there always it errors:

Downloading Frameworks/AmazonFling.framework/Versions/A/AmazonFling (544 MB)
Error downloading object: Frameworks/AmazonFling.framework/Versions/A/AmazonFling (cda6b5c): Smudge error: Error downloading Frameworks/AmazonFling.framework/Versions/A/AmazonFling (cda6b5cab7ed9c4f63f8a366dffffb87900652086ad5bd33b33ea3073f6180f3): batch response: This repository is over its data quota. Purchase more data packs to restore access.

**Comment by crelies** [comment]
I'm sorry for the late answer. The problem is that I have to pay for more Git LFS Data. At the moment I don't plan to spend more money on that.

If there are enough people which want to use this pod I would think about it.
Additionally I would appreciate donations to be able to buy more Git LFS Data. I maintain this pod in my free time.
